version: 2
jobs:
  build:
    working_directory: ~/lorengreenfield/halfcab
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run:
        working_directory: ~/lorengreenfield/halfcab
        command: nvm install 8.11.3 && nvm alias default 8.11.3
    - run: export PATH="~/lorengreenfield/halfcab/node_modules/.bin:$PATH"
    - run: npm install
    - run: npm test
    - run: npm run coverage-report | COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN ./node_modules/.bin/coveralls
