version: 2
jobs:
  build:
    working_directory: ~/lorengreenfield/halfcab
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: cimg/node:18.18.0
    steps:
    - checkout
    - run: export PATH="~/lorengreenfield/halfcab/node_modules/.bin:$PATH"
    - run: npm install
    - run: npm run test:coveralls
